# Analisis exploratorio de datos

## Importacion de librerias

In [2]:
import pandas as pd

## funciones

In [3]:
def Summary(data, sheet):
    print(f"Hoja: {sheet}")

    # Crear la tabla de resumen
    resumen = {
        "Cantidad de filas": data.shape[0],
        "Cantidad de columnas": data.shape[1],
        "Datos faltantes": data.isnull().sum().sum(),
        "Filas duplicadas": data.duplicated().sum()
    }

    # Convertir el resumen en un DataFrame
    ResumenHoja = pd.DataFrame(resumen, index=["Resumen"])
    print("\nResumen:")
    display(ResumenHoja)

    print("\nEncabezado:")
    display(data.head())

In [4]:
def analizar_categoricas(df):
    resultados = {}
    
    # Detectar variables categóricas (object, category o booleanas)
    categoricas = df.select_dtypes(include=['object', 'category', 'bool']).columns
    
    for col in categoricas:
        # Conteo por categoría
        conteo = df[col].value_counts(dropna=False)
        proporcion = df[col].value_counts(normalize=True, dropna=False)
        
        resultados[col] = {
            "cantidad_categorias": df[col].nunique(dropna=False),
            "conteo": conteo.to_dict(),
            "proporcion": proporcion.to_dict()
        }
    
    return resultados

## Introduccion

fuente de los datos: https://archive.ics.uci.edu/dataset/2/adult

### Descripcion general del dataset

- Conocido también como Census Income.

- Fue publicado en el UCI Machine Learning Repository por Barry Becker en 1996, a partir de datos del censo de EE. UU. de 1994.

- Tiene 48 842 instancias y 14 atributos.

### Atributos incluidos

- Age
- Fnlwgt (final weight)
- Education
- Education-num
- Capital-gain
- Capital-loss
- Hours-per-week
- Workclass
- Occupation
- Native-country
- Relationship
- Marital-status
- Race
- Sex
- Income

## Cargado de datos:

In [5]:
df1=pd.read_csv("adult.data",header=None)
df2=pd.read_csv("adult.test",header=None)

In [6]:
df1.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [7]:
df2.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K.
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K.
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K.
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K.
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K.

In [8]:
df = pd.concat([df1, df2], ignore_index=True)

In [9]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [10]:
cols = ["Age",
          "Workclass",
          "Fnlwgt",
          "Education",
          "Education-num",
          "Marital-status",
          "Occupation",
          "Relationship",
          "Race",
          "Sex",
          "Capital-gain",
          "Capital-loss",
          "Hours-per-week",
          "Native-country",
          "Income"]
df.columns = cols
df.head()

,Age,Workclass,Fnlwgt,Education,Education-num,Marital-status,Occupation,Relationship,Race,Sex,Capital-gain,Capital-loss,Hours-per-week,Native-country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

Cargamos el conjunto de datos desde las 2 tablas y como no es nuestro objetivo realizar tecnicas de machine learning juntamos los registros de train y test para formar un dataframe completo con toda la informacion.
Se observa ademas la falta de nombres representativos para las columnas lo cual acaba de ser arreglado

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             48842 non-null  int64
 1   Workclass       48842 non-null  object
 2   Fnlwgt          48842 non-null  int64
 3   Education       48842 non-null  object
 4   Education-num   48842 non-null  int64
 5   Marital-status  48842 non-null  object
 6   Occupation      48842 non-null  object
 7   Relationship    48842 non-null  object
 8   Race            48842 non-null  object
 9   Sex             48842 non-null  object
 10  Capital-gain    48842 non-null  int64
 11  Capital-loss    48842 non-null  int64
 12  Hours-per-week  48842 non-null  int64
 13  Native-country  48842 non-null  object
 14  Income          48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

ademas notamos que el tipo de dato está correctamente entendido por python en el caso de las variables numericas education-num(a pesar de ser un numero es una variable categorica) y la convertiremos a factor

Ahora que ya finalizamos con el cargado y la validacion adecuada del tipo de dato podemos proseguir con un analisis exploratorio de datos con su respectivo analisis de datos faltantes

## Analisis exploratorio de datos

In [12]:
Summary(df, "Datos")

Hoja: Datos

Resumen:

,Cantidad de filas,Cantidad de columnas,Datos faltantes,Filas duplicadas
Resumen,48842,15,0,29

Encabezado:

,Age,Workclass,Fnlwgt,Education,Education-num,Marital-status,Occupation,Relationship,Race,Sex,Capital-gain,Capital-loss,Hours-per-week,Native-country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [13]:
df.describe()

,Age,Fnlwgt,Education-num,Capital-gain,Capital-loss,Hours-per-week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [14]:
analizar_categoricas(df)

{'Workclass': {'cantidad_categorias': 9,
  'conteo': {' Private': 33906,
   ' Self-emp-not-inc': 3862,
   ' Local-gov': 3136,
   ' ?': 2799,
   ' State-gov': 1981,
   ' Self-emp-inc': 1695,
   ' Federal-gov': 1432,
   ' Without-pay': 21,
   ' Never-worked': 10},
  'proporcion': {' Private': 0.6941976168052086,
   ' Self-emp-not-inc': 0.07907129110192047,
   ' Local-gov': 0.06420703492895459,
   ' ?': 0.05730723557593874,
   ' State-gov': 0.04055935465378158,
   ' Self-emp-inc': 0.034703738585643504,
   ' Federal-gov': 0.029319028704803244,
   ' Without-pay': 0.0004299578231849638,
   ' Never-worked': 0.00020474182056426845}},
 'Education': {'cantidad_categorias': 16,
  'conteo': {' HS-grad': 15784,
   ' Some-college': 10878,
   ' Bachelors': 8025,
   ' Masters': 2657,
   ' Assoc-voc': 2061,
   ' 11th': 1812,
   ' Assoc-acdm': 1601,
   ' 10th': 1389,
   ' 7th-8th': 955,
   ' Prof-school': 834,
   ' 9th': 756,
   ' 12th': 657,
   ' Doctorate': 594,
   ' 5th-6th': 509,
   ' 1st-4th': 247,
   ' Preschool': 83},
  'proporcion': {' HS-grad': 0.32316448957864136,
   ' Some-college': 0.22271815240981122,
   ' Bachelors': 0.16430531100282544,
   ' Masters': 0.05439990172392613,
   ' Assoc-voc': 0.04219728921829573,
   ' 11th': 0.03709921788624544,
   ' Assoc-acdm': 0.03277916547233938,
   ' 10th': 0.02843863887637689,
   ' 7th-8th': 0.01955284386388764,
   ' Prof-school': 0.01707546783505999,
   ' 9th': 0.015478481634658696,
   ' 12th': 0.013451537611072437,
   ' Doctorate': 0.012161664141517547,
   ' 5th-6th': 0.010421358666721264,
   ' 1st-4th': 0.0050571229679374306,
   ' Preschool': 0.0016993571106834282}},
 'Marital-status': {'cantidad_categorias': 7,
  'conteo': {' Married-civ-spouse': 22379,
   ' Never-married': 16117,
   ' Divorced': 6633,
   ' Separated': 1530,
   ' Widowed': 1518,
   ' Married-spouse-absent': 628,
   ' Married-AF-spouse': 37},
  'proporcion': {' Married-civ-spouse': 0.45819172024077637,
   ' Never-married': 0.32998239220343145,
   ' Divorced': 0.13580524958027926,
   ' Separated': 0.031325498546333076,
   ' Widowed': 0.031079808361655952,
   ' Married-spouse-absent': 0.012857786331436059,
   ' Married-AF-spouse': 0.0007575447360877933}},
 'Occupation': {'cantidad_categorias': 15,
  'conteo': {' Prof-specialty': 6172,
   ' Craft-repair': 6112,
   ' Exec-managerial': 6086,
   ' Adm-clerical': 5611,
   ' Sales': 5504,
   ' Other-service': 4923,
   ' Machine-op-inspct': 3022,
   ' ?': 2809,
   ' Transport-moving': 2355,
   ' Handlers-cleaners': 2072,
   ' Farming-fishing': 1490,
   ' Tech-support': 1446,
   ' Protective-serv': 983,
   ' Priv-house-serv': 242,
   ' Armed-Forces': 15},
  'proporcion': {' Prof-specialty': 0.1263666516522665,
   ' Craft-repair': 0.12513820072888088,
   ' Exec-managerial': 0.12460587199541379,
   ' Adm-clerical': 0.11488063551861104,
   ' Sales': 0.11268989803857336,
   ' Other-service': 0.10079439826378936,
   ' Machine-op-inspct': 0.06187297817452193,
   ' ?': 0.05751197739650301,
   ' Transport-moving': 0.04821669874288522,
   ' Handlers-cleaners': 0.04242250522091642,
   ' Farming-fishing': 0.030506531264076,
   ' Tech-support': 0.029605667253593218,
   ' Protective-serv': 0.02012612096146759,
   ' Priv-house-serv': 0.004954752057655297,
   ' Armed-Forces': 0.00030711273084640267}},
 'Relationship': {'cantidad_categorias': 6,
  'conteo': {' Husband': 19716,
   ' Not-in-family': 12583,
   ' Own-child': 7581,
   ' Unmarried': 5125,
   ' Wife': 2331,
   ' Other-relative': 1506},
  'proporcion': {' Husband': 0.4036689734245117,
   ' Not-in-family': 0.257626632816019,
   ' Own-child': 0.15521477416977192,
   ' Unmarried': 0.10493018303918758,
   ' Wife': 0.04772531837353098,
   ' Other-relative': 0.030834118176978828}},
 'Race': {'cantidad_categorias': 5,
  'conteo': {' White': 41762,
   ' Black': 4685,
   ' Asian-Pac-Islander': 1519,
   ' Amer-Indian-Eskimo': 470,
   ' Other': 406},
  'proporcion': {' White': 0.855042791040498,
   ' Black': 0.09592154293435977,
   ' Asian-Pac-Islander': 0.031100282543712377,
   ' Amer-Indian-Eskimo': 0.009622865566520618,
   ' Other': 0.0083125179149093}},
 'Sex': {'cantidad_categorias': 2,
  'conteo': {' Male': 32650, ' Female': 16192},
  'proporcion': {' Male': 0.6684820441423365, ' Female': 0.33151795585766347}},
 'Native-country': {'cantidad_categorias': 42,
  'conteo': {' United-States': 43832,
   ' Mexico': 951,
   ' ?': 857,
   ' Philippines': 295,
   ' Germany': 206,
   ' Puerto-Rico': 184,
   ' Canada': 182,
   ' El-Salvador': 155,
   ' India': 151,
   ' Cuba': 138,
   ' England': 127,
   ' China': 122,
   ' South': 115,
   ' Jamaica': 106,
   ' Italy': 105,
   ' Dominican-Republic': 103,
   ' Japan': 92,
   ' Guatemala': 88,
   ' Poland': 87,
   ' Vietnam': 86,
   ' Columbia': 85,
   ' Haiti': 75,
   ' Portugal': 67,
   ' Taiwan': 65,
   ' Iran': 59,
   ' Greece': 49,
   ' Nicaragua': 49,
   ' Peru': 46,
   ' Ecuador': 45,
   ' France': 38,
   ' Ireland': 37,
   ' Thailand': 30,
   ' Hong': 30,
   ' Cambodia': 28,
   ' Trinadad&Tobago': 27,
   ' Outlying-US(Guam-USVI-etc)': 23,
   ' Laos': 23,
   ' Yugoslavia': 23,
   ' Scotland': 21,
   ' Honduras': 20,
   ' Hungary': 19,
   ' Holand-Netherlands': 1},
  'proporcion': {' United-States': 0.8974243478973015,
   ' Mexico': 0.019470947135661932,
   ' ?': 0.017546374022357807,
   ' Philippines': 0.006039883706645919,
   ' Germany': 0.00421768150362393,
   ' Puerto-Rico': 0.0037672494983825395,
   ' Canada': 0.003726301134269686,
   ' El-Salvador': 0.0031734982187461612,
   ' India': 0.0030916014905204535,
   ' Cuba': 0.002825437123786905,
   ' England': 0.0026002211211662092,
   ' China': 0.002497850210884075,
   ' South': 0.0023545309364890873,
   ' Jamaica': 0.0021702632979812455,
   ' Italy': 0.002149789115924819,
   ' Dominican-Republic': 0.002108840751811965,
   ' Japan': 0.0018836247491912698,
   ' Guatemala': 0.0018017280209655625,
   ' Poland': 0.0017812538389091355,
   ' Vietnam': 0.0017607796568527088,
   ' Columbia': 0.0017403054747962819,
   ' Haiti': 0.0015355636542320134,
   ' Portugal': 0.0013717701977805986,
   ' Taiwan': 0.001330821833667745,
   ' Iran': 0.001207976741329184,
   ' Greece': 0.0010032349207649155,
   ' Nicaragua': 0.0010032349207649155,
   ' Peru': 0.0009418123745956349,
   ' Ecuador': 0.0009213381925392081,
   ' France': 0.0007780189181442202,
   ' Ireland': 0.0007575447360877933,
   ' Thailand': 0.0006142254616928053,
   ' Hong': 0.0006142254616928053,
   ' Cambodia': 0.0005732770975799517,
   ' Trinadad&Tobago': 0.0005528029155235249,
   ' Outlying-US(Guam-USVI-etc)': 0.00047090618729781744,
   ' Laos': 0.00047090618729781744,
   ' Yugoslavia': 0.00047090618729781744,
   ' Scotland': 0.0004299578231849638,
   ' Honduras': 0.0004094836411285369,
   ' Hungary': 0.0003890094590721101,
   ' Holand-Netherlands': 2.0474182056426847e-05}},
 'Income': {'cantidad_categorias': 4,
  'conteo': {' <=50K': 24720, ' <=50K.': 12435, ' >50K': 7841, ' >50K.': 3846},
  'proporcion': {' <=50K': 0.5061217804348717,
   ' <=50K.': 0.25459645387166785,
   ' >50K': 0.16053806150444289,
   ' >50K.': 0.07874370418901765}}}